# Generated by Django 4.1.5 on 2023-01-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('isbm', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('auteur', models.CharField(max_length=30)),
                ('editioin', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=30)),
                ('exemplaire', models.CharField(max_length=30)),
                ('domaine', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('photo', models.FileField(upload_to='photos')),
            ],
        ),
    ]
