# Generated by Django 4.1.5 on 2023-01-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'ordering': ['-created_on'], 'verbose_name': 'Livre'},
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='created_on',
            field=models.DateField(default=False, null=True),
        ),
    ]
