# Generated by Django 4.1.5 on 2023-01-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_bookmodel_options_bookmodel_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'Livre'},
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='created_on',
        ),
    ]
