# Generated by Django 4.1.5 on 2023-01-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
